### ISSUE TITLE
css for footer

### ISSUE THREAD

**Issue by rahul0705** [pages-themes/hacker#12]
Any chance we will get some footer CSS?

**Comment by benbalter** [comment]
Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?

**Comment by rahul0705** [comment]
Yes, when adding a footer into the page, there doesn't seem to be any CSS applied to items within the <footer></footer> tags

**Comment by ShixiangWang** [comment]
I have the same issue, how can I add a custom footer for all GitHub pages, like copyright?  I find cayman theme has implemented it https://github.com/pietromenna/jekyll-cayman-theme/blob/master/_includes/page-footer.html.

Thanks.
Shixiang
