### ISSUE TITLE
option to disable "show on github" button

### ISSUE THREAD

**Issue by bararchy** [pages-themes/hacker#14]
I can't find any option for it, what is the right syntax to remove this button from generated pages ?

**Comment by Nierrrrrrr** [comment]
You can change the HTML layout by [Layouts](https://github.com/pages-themes/hacker#layouts).

Just remove the section part from line 19 to 25.

**Comment by darthwalsh** [comment]
A simpler solution is to [customize your site CSS](https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/#customizing-your-jekyll-themes-css) to hide the header by creating the file:

/assets/css/style.scss

```
---
---

@import "{{ site.theme }}";

header {
  display: none;
}
```

**Comment by Psycotropy** [comment]
sdfsdf
