### ISSUE TITLE
How can I add my new posts to a sub folder?

### ISSUE THREAD

**Issue by capsl0cker** [pages-themes/hacker#17]
Hi,
Thanks for make a such cool theme! I like it very much.
But now I have one question, I want to add a new post to a folder because I don't want to mix these 'meta pages' with my own blog posts. 
How can I make it? I try add a folder and add page under it but seems it can't be accessed.

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸

**Comment by Gavitron** [comment]
I was just looking into this same problem, and I think I have an answer for you;  it's not obvious, but I don't think github pages support this out of the box, without actually installing jekyll locally and then building some more robust page templates.

I found a repository [here](https://github.com/tocttou/hacker-blog) which appears to have extended this theme into a full blog, where you can just create posts in a `_posts` directory, without having to install jekyll locally. (though it wouldn't hurt.)
