### ISSUE TITLE
Gem File

### ISSUE THREAD

**Issue by shhivam** [pages-themes/hacker#28]
My doubt, I think, is very stupid but please try to bear this with a novice.

Here is my doubt:

I want to recreate my own Gem file so that I can add relative links. 
Which file should I create and by which name and under which new directories?
I see from one of the pull request that there is already-added-template for posts but there is no documentation telling how to use that feature. Is there any way I can use that template?

I am hosting Github pages using `/docs` folder.

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
