### ISSUE TITLE
Allow to change the download links and view on Github

### ISSUE THREAD

**Issue by devnoname120** [pages-themes/hacker#3]
https://github.com/pages-themes/hacker/blob/0c80ff632d2c283a8165a6cd7313f0a26292b0a6/_layouts/default.html#L18-L22

I would like to be able to replace the downloads links in [`_config.yml`](https://github.com/pages-themes/hacker/blob/0c80ff632d2c283a8165a6cd7313f0a26292b0a6/_config.yml) without using a hacky solution.

**Comment by benbalter** [comment]
@devnoname120 to clarify, you'd like to point to an arbitrary URL?

**Comment by devnoname120** [comment]
Yes, but I figured out that modifying the layout allows me to do this. I think that this issue can be closed since it solves my problem.

It seems rather rare to me though that one would want the download link to point to an archive of the site repository.

**Comment by devnoname120** [comment]
Thanks! I will close this issue as my problem is solved.
