### ISSUE TITLE
<hr> doesn't look like it's supposed to do

### ISSUE THREAD

**Issue by AlexejheroYTB** [pages-themes/hacker#31]
I have created a website for a Subnautica mod/library and I found out something peculiar:
Every second `<hr>` looks a bit thinner that it is supposed to do

The difference is very visible, especially on the live website.

![image](https://user-images.githubusercontent.com/32238504/46574558-cb2c3f80-c9ad-11e8-89ae-40ec069d6301.png)
![image](https://user-images.githubusercontent.com/32238504/46574561-d4b5a780-c9ad-11e8-9c89-c006937badd2.png)

The link to the website is: https://smlhelper.github.io/
**Note: You will need to disable JavaScript on the website to see the secondary layout which uses `<hr>` elements**

I am not sure if this is an issue with the theme, github, or even html itself.
I did not find anything that could cause this in the css files.

**Comment by danjonesdev** [comment]
@AlexejheroYTB Hi, what browser are you viewing this in? I'm unable to recreate this issue,

**Comment by AlexejheroYTB** [comment]
Google Chrome, 69.0.3497.100 64-bit

**Comment by kjhx** [comment]
Likewise unable to recreate this issue in `Safari 12.0 (14606.1.36.1.9)`.

**Comment by eng1nerd** [comment]
I tried to recreate this issue in `Firefox Quantum 62.0.3` and `Safari 12.0.1 (13606.2.104.1.2)`, but it's unsuccessful.

**Comment by AlexejheroYTB** [comment]
Then I don't know. 
~~~
~~~
~~~
~~~
