### ISSUE TITLE
CSS customization not working

### ISSUE THREAD

**Issue by ousia** [pages-themes/hacker#4]
I’m afraid that I’m following the instructions explained at https://github.com/pages-themes/hacker#stylesheet (see https://github.com/ousia/aprender-linux/blob/master/assets/css/style.css), but customized data aren’t loaded at all.

Am I missing something or have I hit a bug?

Many thanks for your help and Happy New Year!!!

**Comment by benbalter** [comment]
@ousia it should be `style.scss` (note the "S"). I'll get a PR open to update the typo in the docs.

**Comment by benbalter** [comment]
Docs updated via https://github.com/pages-themes/hacker/commit/6f38408cfb1049f335a8466b06ef2e651e3b969a.

**Comment by ousia** [comment]
Many thanks for the explanation, @benbalter.

> It was a small letter for the hacker, but a huge website for the rest of us :smile:.

**Comment by ousia** [comment]
I forgot to close the issue.
