### ISSUE TITLE
Cannot get rid of "View on Github" Button

### ISSUE THREAD

**Issue by ucalyptus** [pages-themes/hacker#45]
Tried the solution mentioned in https://github.com/pages-themes/cayman/issues/29  but that didn't work as expected.

**Comment by MouxiaoHuang** [comment]
maybe u can add
github:
    is_project_page: false
in your _config.yml

**Comment by haisekazuto** [comment]
yep that did not work for me either

**Comment by ucalyptus** [comment]
I solved it. Customize as written on the readme.md and then in the _layouts/default.html

You can remove wherever it is written as View on Github

**Comment by dariocast** [comment]
This issue is closed, however I still haven't found a way to remove the View on github button without removing the full header section via style.scss
Anyone can explain the solution? I host on github pages
