### ISSUE TITLE
automatic anchor links for headers

### ISSUE THREAD

**Issue by vapier** [pages-themes/hacker#48]
github automatically generates links for all headers in markdown files.  the themes should too.

for example, viewing this repo:
https://github.com/pages-themes/hacker
if you mouse over "The Hacker theme" or "Usage", a little link shows up for easy clicking/copying.

**Comment by vapier** [comment]
the request is still relevant.  does this project accept FRs ?

**Comment by PsychoData** [comment]
I believe this theme already adds these headerlinks to the headers from github (or at least possibly keeps them from the Github page? I'm not certain) 

On Github, the headers automatically get a link image that appears when you hover over it, which is useful to right-click and copy the link address directly to that section
![image](https://user-images.githubusercontent.com/3719116/97667704-dcde5500-1a56-11eb-8652-de42d0c230b9.png)

On this theme's pages, it seems like the anchors are already created, and if you manually find them and create a link to them, they work, like this
https://msportals.xyz/#azure-it-admin-portals 
![image](https://user-images.githubusercontent.com/3719116/97667840-2890fe80-1a57-11eb-81aa-affff05387ec.png)

Could we possibly add something to let you copy the links directly to a section/header more easily? 
It looks like [AnchorJS](https://github.com/bryanbraun/anchorjs/releases) might work, but I am not certain how to integrate it into the theme

**Comment by vapier** [comment]
the request was about the UI side of things which the theme doesn't do

**Comment by PsychoData** [comment]
Oh? I thought that since this theme has the anchors created, but other themes don't, that the theme or something it was using is what was creating the anchors 

any idea what might be creating the anchors? Since they are already there once I add the theme, I don't think that trying to recreate them again with AnchorJS like I mentioned above would work correctly, since they would be conflicting

**Comment by PsychoData** [comment]
wait, I had a bad file - if I remove the Jekyll Theme, then my site looks like this and has working header clickable links
![image](https://user-images.githubusercontent.com/3719116/97713411-2bf7aa80-1a96-11eb-927b-61a5ae102b72.png)

and the code looks like this, so I'm not sure where the whole `<a>`  element goes once the theme is enabled, but the same anchor appears in the header element directly instead 
![image](https://user-images.githubusercontent.com/3719116/97713762-a294a800-1a96-11eb-88ba-bc4e256d3099.png)

**Comment by vapier** [comment]
those pictures aren't using the hacker theme.  see this page as an example of missing UI elements:
https://vapier.github.io/nosig/

**Comment by PsychoData** [comment]
That's my point though, when I remove the theme, the automatic clickable links are there 
![image](https://user-images.githubusercontent.com/3719116/97872777-99991600-1ce4-11eb-897f-973ee4100f1f.png)


but when the Hacker theme is added back, they are gone 
![image](https://user-images.githubusercontent.com/3719116/97872804-a1f15100-1ce4-11eb-944b-162ce085b592.png)

**Comment by vapier** [comment]
well, sure, the default theme has the clickable links.  that's why this issue is filed against the hacker theme which lacks them.
