### ISSUE TITLE
How to set up ad sense, comments

### ISSUE THREAD

**Issue by alexharv074** [pages-themes/hacker#51]
This is a request for support, sorry if it's the wrong place to ask! I am trying to set up Google Ad Sense and also Disqus Comments. I couldn't figure out why none of the blogs out there showing how to do these things were working until I finally realised that this (awesome) Jekyll-theme-hacker owns the [default](https://github.com/pages-themes/hacker/blob/master/_layouts/default.html) and [post](https://github.com/pages-themes/hacker/blob/master/_layouts/post.html) layout I use. I also see in the code there conditional logic for Google Analytics. So I'm confused about what I need to do to set up Ad Sense and Comments. Do I need to PR features for these into here, or is there some documentation I should have read?

**Comment by xirsoi** [comment]
The default and post layouts can be overriden by you. All you need to to is create a _layouts folder and put your override of the layout in there. I recommend copying the existing layout (found in this repo) and modifying it.

As for google analytics, you need to sign up for an AdSense account and get your unique code, then add it in your _config.yaml like this 'google_analytics: my_adsense_code' and the layout will take care of the rest.

**Comment by xirsoi** [comment]
Just looked at your repo, remove the underscore from the beginning of the layout name. default.html not _default.html
