### ISSUE TITLE
Bullet points for unordered list

### ISSUE THREAD

**Issue by tianyunwu** [pages-themes/hacker#7]
I am wondering if there is an way to use bullet point as the symbol of unordered list? I followed the kramdown syntax and used the the asterisk symbol (*) to mark list elements, but the html output gave me something that looked like right shrift operator. Is it something that I should expect from using this Jekyll theme? Thank you in advance for helping me out!

**Comment by benbalter** [comment]
@tianyunwu Can you provide a screenshot of your output?

**Comment by tianyunwu** [comment]
@benbalter 
Here is the markdown snippet:
![image](https://cloud.githubusercontent.com/assets/9081407/22185740/038f3510-e0b9-11e6-9ed5-f98b9d199709.png)
Here is the corresponding output:
![image](https://cloud.githubusercontent.com/assets/9081407/22185743/1cbb321e-e0b9-11e6-8465-b34ef4c96327.png)
As you can see, the symbol used to mark each entry of the unordered list is a right shrift operator ('>>'), should I modify the CSS files to get the following effect:

This is a test.

* this is test 1.0
* this is test 2.0
* this is test 3.0

**Comment by p0gr0mist** [comment]
Hello @tianyunwu !

> Is it something that I should expect from using this Jekyll theme?

Yes. 
Asterisk symbol (*), hyphen symbol (-) and symbol plus (+) have same meaning in Markdown. And standard output for this will be bullet point, but this theme uses shift operator.
But you can customize this for yourself, just put this in ```assets/css/style.scss```:

```scss
ul li {
  list-style: disc;
}

ul li:before {
    content: none
}
```

**Comment by tianyunwu** [comment]
@p0gr0mist Thank you very much!
