### ISSUE TITLE
The hacker theme is not currently supported on GitHub Pages.

### ISSUE THREAD

**Issue by AnonyPla** [pages-themes/hacker#77]
Since yesterday (07/22/2021) I constantly get the following error:

" The page build failed for the main branch with the following error: The hacker theme is not currently supported on GitHub Pages. "

No weird changes were made and it was working fine the day before. 

![Capture](https://user-images.githubusercontent.com/86740652/126808741-087465b7-e122-4753-9096-4c40fa30bb3d.jpg)

![Capture2](https://user-images.githubusercontent.com/86740652/126808760-6201ed89-15db-4236-8182-05ff624a461c.jpg)

**Comment by parkr** [comment]
Hey @AnonyPla, could you please try again now and tell me if it's working?

**Comment by AnonyPla** [comment]
Yup problem solved

**Comment by AnonyPla** [comment]
Small comment ... I still have the "issue" when trying to build locally with bundle ...

**Comment by AnonyPla** [comment]
Yes it seems this issue is also propagated onto an updated bundle locally ...

`jekyll 3.9.0 | Error:  The jekyll-theme-hacker theme could not be found.`

`theme.rb:84:in `rescue in gemspec': The jekyll-theme-hacker theme could not be found. (Jekyll::Errors::MissingDependencyException)`

`dependency.rb:311:in `to_specs': Could not find 'jekyll-theme-hacker' (>= 0) among 163 total gem(s) (Gem::MissingSpecError)`

Using github-pages 216

**Comment by cipy** [comment]
yes, still breaks as in #76

**Comment by AnonyPla** [comment]
If you still have issues to build locally, consider looking at https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882
