### ISSUE TITLE
ordered list inside unordered list

### ISSUE THREAD

**Issue by p0gr0mist** [pages-themes/hacker#8]
Hello @benbalter !
I have problem that is related to ordered list inside unordered list. All numbers inside ```<ul></ul>``` tags are replaced by shift operators because rule ```ul li:before``` in ```_sass/jekyll-theme-hacker.scss``` applies to all ```li```.
For example,
input:
```markdown
Test

- bla bla bla
- bla bla bla
   1. bla bla bla
   2. bla bla bla
   3. bla bla bla
- bla bla bla
- bla bla bla

Test
```

output:
![list](https://cloud.githubusercontent.com/assets/18351400/22392644/9c61b6c8-e4c9-11e6-8ea2-7120366d147e.png)

How to fix it?

**Comment by benbalter** [comment]
@p0gr0mist I believe you discovered the solution via https://github.com/pages-themes/hacker/issues/7#issuecomment-275809959. That is a stylistic choice of the theme author.
