### ISSUE TITLE
no working in my github page

### ISSUE THREAD

**Issue by mudongliang** [pages-themes/hacker#9]
I add this hacker theme to my github page with [commit 6cfb67d4d33](https://github.com/mudongliang/mudongliang.github.io/commit/6cfb67d4d33efc74d9a29e697bbb27db39b2d814]).

However, it doesn't work. [My website](http://mudongliang.github.io/) still has a white Index Page.

Do I miss some key steps?

**Comment by joisadler** [comment]
I have the same problem :(

**Comment by benbalter** [comment]
We can't speak to the specifics of your local setup. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
