### ISSUE TITLE
programmer

### ISSUE THREAD

**Issue by rezacco** [pages-themes/hacker#96]

**Comment by rabooli** [comment]
در تاریخ شنبه ۲۲ ژانویهٔ ۲۰۲۲،‏ ۱۰:۳۶ no-response[bot] <
***@***.***> نوشت:

**Comment by rabooli** [comment]
Hajrasool007

در تاریخ شنبه ۲۹ ژانویهٔ ۲۰۲۲،‏ ۰۷:۰۱ rabooli ***@***.***>
نوشت:

**Comment by rabooli** [comment]
Hajrasool007

در تاریخ یکشنبه ۶ فوریهٔ ۲۰۲۲،‏ ۲۰:۲۹ rabooli ***@***.***>
نوشت:

**Comment by rabooli** [comment]
My phone is samsung


Hajrasool007

در تاریخ یکشنبه ۶ فوریهٔ ۲۰۲۲،‏ ۲۰:۳۴ rabooli ***@***.***>
نوشت:
